Ajuste mitigação Log4J All-in-one
Sensedia/api-platform-hybrid pull request #21
Opened 2021-12-20 17:30 UTC by alanchiosini

**O que foi feito?**

Alteração do  "LOGGING_LEVEL_COM_SENSEDIA= " para o valor de ERROR
Adição da flag Dlog4j2.formatMsgNoLookups=True  no JAVA_OPTS

**Por que foi feito?**
Mitigação para Log4J

2021-12-20 17:50 UTC, fmengue approved these changes
OK.

2021-12-20 18:00 UTC, ClaudenirFreitas requested changes

2021-12-20 18:00 UTC, ClaudenirFreitas commented on compose/all-in-one/hybrid.env
> +JAVA_OPTS=-Djava.security.egd="file:/dev/./urandom -Dfile.encoding=UTF8 -Xmx512m -Dlog4j2.formatMsgNoLookups=True -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.ForkJoinPool.commo
deve ser `true` ao invés de `True`. Sendo: `-Dlog4j2.formatMsgNoLookups=true`

2021-12-20 21:22 UTC, aeciopires commented on compose/all-in-one/hybrid.env
> +JAVA_OPTS=-Djava.security.egd="file:/dev/./urandom -Dfile.encoding=UTF8 -Xmx512m -Dlog4j2.formatMsgNoLookups=True -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.ForkJoinPool.commo
Oi, @ClaudenirFreitas!
O valor é insensitive case. @alanwds testou com maiúsculo, inclusive e conseguiu validar a mudança no comportamento.

2021-12-20 21:22 UTC, aeciopires approved these changes

2021-12-21 18:21 UTC, ClaudenirFreitas commented on compose/all-in-one/hybrid.env
> +JAVA_OPTS=-Djava.security.egd="file:/dev/./urandom -Dfile.encoding=UTF8 -Xmx512m -Dlog4j2.formatMsgNoLookups=True -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.ForkJoinPool.commo
Ah perfeito Aécio!
Realmente, [tal configuração](https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/util/Constants.java) é _[case insensitive](https://github.com/apache/logging-log4j2/blob/rel/2.14.1/log4j-api/src/main/java/org/apache/logging/log4j/util/PropertiesUtil.java#L142)_. Foi mal!

2021-12-21 18:22 UTC, ClaudenirFreitas approved these changes

2021-12-27 20:45 UTC, merged