Ajuste Mitigação Log4J
Sensedia/api-platform-hybrid pull request #22
Opened 2021-12-20 17:33 UTC by alanchiosini

**O que foi feito?**
Adição da flag Dlog4j2.formatMsgNoLookups=True  no JAVA_OPTS

**Por que foi feito?**
Mitigação para Log4J

2021-12-20 18:04 UTC, ClaudenirFreitas requested changes

2021-12-20 18:04 UTC, ClaudenirFreitas commented on kubernetes/helm/values_examples/api-gateway/values.yaml
> +  java_opts: "-Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=True -Dfile.encoding=UTF8 -Xms1536m -Xmx1536m -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.Fork
deve ser `true` ao invés de `True`. Sendo: `-Dlog4j2.formatMsgNoLookups=true`.
Poderia verificar?

2021-12-20 21:25 UTC, aeciopires commented on kubernetes/helm/values_examples/api-gateway/values.yaml
> +  java_opts: "-Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=True -Dfile.encoding=UTF8 -Xms1536m -Xmx1536m -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.Fork
Oi, @ClaudenirFreitas!
O valor é insensitive case. @alanwds testou com maiúsculo, inclusive e conseguiu validar a mudança no comportamento.

2021-12-20 21:26 UTC, aeciopires approved these changes

2021-12-21 18:22 UTC, ClaudenirFreitas commented on kubernetes/helm/values_examples/api-gateway/values.yaml
> +  java_opts: "-Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=True -Dfile.encoding=UTF8 -Xms1536m -Xmx1536m -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.Fork
Ah perfeito Aécio!
Realmente, [tal configuração](https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/util/Constants.java) é _[case insensitive](https://github.com/apache/logging-log4j2/blob/rel/2.14.1/log4j-api/src/main/java/org/apache/logging/log4j/util/PropertiesUtil.java#L142)_. Foi mal!

2021-12-21 18:22 UTC, ClaudenirFreitas approved these changes

2021-12-27 20:45 UTC, merged